# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zEEDGO9prrpfp-GaPb198Nwtre-eai12
"""

# -*- coding: utf-8 -*-
"""Untitled7.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1JruPU6A2-AXb7UaWbhAsa_6eHOarsB5h
"""

# program to plot CDF
import math
import numpy as np 
import matplotlib.pyplot as plot

#defining the function for the CDF
def F_X(x):
  if(x<-1):
    return 0
  elif(x>=-1) and (x<2):
    return (x+1)/3
  elif(x>=2):
    return 1;
  else:
    return 0  

    #plotting Cdf 
X = np.linspace(-5,6,10000000)

Y = [F_X(x) for x in X]
plot.xlabel('x')
plot.ylabel('$F_X(x)$')
plot.plot(X,Y)

plot.grid()
plot.show()