# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xQeLlNYBbBBYR5FbaU-rMG80Ex-Ty1Xq
"""

# -*- coding: utf-8 -*-
"""Untitled1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1KG8wynBSI-DVcMeEyY_QOG97GuBA6hCV
"""

# -*- coding: utf-8 -*-
"""Untitled1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1KG8wynBSI-DVcMeEyY_QOG97GuBA6hCV
"""

# -*- coding: utf-8 -*-
"""Untitled1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1KG8wynBSI-DVcMeEyY_QOG97GuBA6hCV
"""

"""Untitled1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1KG8wynBSI-DVcMeEyY_QOG97GuBA6hCV
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
from scipy.stats import norm
from scipy.stats import binom
import random 

count=0;
z=0
n=16   # n i s total number of balls
q=8    # p is total number of green balls
a=0
while a<1000000:
   r=random.randint(1,n)
   if r>q:
      count+=1
   a+=1
p1=count/a
print(f'the probability that the first ball drawn is red is : {count/a}')     

a=0
count=0

while a<1000000:
   r=random.randint(1,n-1)
   if r>n-1-q:
      count+=1
   a+=1
p2=count/a
print(f'the probability that the second ball drawn is green is : {count/a}')


print(f'The probability that the first ball drawn is red and the second ball drawn is green is :{(p1)*(p2)}')# as p1